config/routes.rb
Rails.application.routes.draw do

   root 'posts#index'

   get 'posts/:id' => 'posts#show', as: :post

   get 'about' => 'authors#about', as: :about

   get 'authors' => 'authors#index', as: :authors

   get ':last_name' => 'posts#by_author', as: :author_posts

end

app/models/author.rb
class Author
  attr_accessor :first_name, :last_name, :bio

  def initialize(hash)
    @first_name = hash[:first_name]
    @last_name  = hash[:last_name]
    @bio        = hash[:bio]
  end

  def self.all
    unless defined?(@@authors)
      @@authors = [
          Author.new(
            :first_name     => "Anthony",
            :last_name      => "Burgess",
            :bio            => "John Anthony Burgess Wilson, (25 February 1917 – 22 November 1993) – who published under the pen name Anthony Burgess – was an English writer and composer. From relatively modest beginnings in a Catholic family in Manchester, he eventually became one of the best known English literary figures of the latter half of the twentieth century. Although Burgess was predominantly a comic writer, his dystopian satire A Clockwork Orange remains his best known novel."
          ),
          Author.new(
            :first_name     => "Ken",
            :last_name      => "Kesey",
            :bio            => "Kenneth Elton 'Ken' Kesey (September 17, 1935 – November 10, 2001) was an American author, best known for his novel One Flew Over the Cuckoo's Nest (1962)[1] and as a countercultural figure who considered himself a link between the Beat Generation of the 1950s and the hippies of the 1960s. 'I was too young to be a beatnik, and too old to be a hippie,'' Kesey said in a 1999 interview with Robert K. Elder."
          ),
          Author.new(
            :first_name     => "Kurt",
            :last_name      => "Vonnegut",
            :bio            => "Kurt Vonnegut, Jr. (November 11, 1922 – April 11, 2007) was an American writer and humorist. In a career spanning over 50 years, Vonnegut published fourteen novels, three short story collections, five plays and five works of non-fiction. He is most famous for his darkly satirical, best-selling novel Slaughterhouse-Five, which tells of the life of Billy Pilgrim."
          ),
          Author.new(
            :first_name     => "Ray",
            :last_name      => "Bradbury",
            :bio            => "Ray Douglas Bradbury (22 August 1920 – 5 June 2012) was an American fantasy, science fiction, horror and mystery fiction author. Best known for his dystopian novel Fahrenheit 451 (1953) and for the science fiction and horror stories gathered together as The Martian Chronicles (1950) and The Illustrated Man (1951), Bradbury was one of the most celebrated 20th- and 21st-century American genre writers. He wrote and consulted on many screenplays and television scripts, including Moby Dick and It Came from Outer Space. Many of his works have been adapted into comic books, television shows, and films."
          ),
          Author.new(
            :first_name     => "Doc",
            :last_name      => "Brown",
            :bio            => "Doc Brown is the creator and mastermind behind The Dead Writer's Delorean. While he does not write any articles, it is through his inventive genius that we are able to glean wisdom from our favorite authors post-mortem."
          )
      ]
    end
    @@authors
  end

  def self.find(last_name)
    all.select{|author| author.last_name == last_name}.first
  end

  def show_name
    "#{@first_name} #{@last_name}"
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index #index usually shows a list
    @authors = Author.all
    @title = "About Our Time Travelers"
    @subheading = "Your favorite authors who have kicked the bucket."
  end

  def about
    @title = "About the Dead Writer's Delorean"
    @subheading = "Brought to you by Doc Brown and 1.21 Gigawatts!"
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/about.html.erb
  <div id="brown" class="author-image">
  </div>
  <div class="author-info">
    <h3 class="author-title">
        <%= Author.find("Brown").show_name %>
    </h3>
    <p class="author-bio">
        <%= Author.find("Brown").bio %>
    </p>
  </div>
  <p>Here Doc Brown describes his invention:</p>
  <blockquote>He's absolutely right, Marty. the last thing you need is headaches. Hot, Jesus Christ, Doc. Jesus Christ, Doc, you disintegrated Einstein. Doc, Doc, it's me, Marty. Which one's your pop? I guarantee it.

I gotta go, uh, I gotta go. Thanks very much, it was wonderful, you were all great. See you all later, much later. Who? When could weathermen predict the weather, let alone the future. whoa, whoa Doc, stuck here, I can't be stuck here, I got a life in 1985. I got a girl. He's fine, and he's completely unaware that anything happened. As far as he's concerned the trip was instantaneous. That's why Einstein's watch is exactly one minute behind mine. He skipped over that minute to instantly arrive at this moment in time. Come here, I'll show you how it works. First, you turn the time circuits on. This readout tell you where you're going, this one tells you where you are, this one tells you where you were. You imput the destination time on this keypad. Say, you wanna see the signing of the declaration of independence, or witness the birth or Christ. Here's a red-letter date in the history of science, November 5, 1955. Yes, of course, November 5, 1955.

It's cold, damn cold. Ha, ha, ha, Einstein, you little devil. Einstein's clock is exactly one minute behind mine, it's still ticking. Biff, stop it. Biff, you're breaking his arm. Biff, stop. Oh, just a little weather experiment. What, what, ma? Listen, this is very important, I forgot my video camera, could you stop by my place and pick it up on your way to the mall?</blockquote>
<h3><%=link_to "About our Time Travelers", authors_path%></h3>

app/views/authors/index.html.erb
<%@authors.each do |author|%>
  <div id="<%=author.last_name.downcase%>" class="author-image">
  </div>
  <div class="author-info">
    <h3 class="author-title">
        <%= author.show_name %>
    </h3>
    <p class="author-bio">
        <%= author.bio %>
    </p>
  </div>
  <hr/>
<% end %>