config/routes.rb
Rails.application.routes.draw do

   root 'posts#index'

   get 'posts/:id' => 'posts#show', as: :post

   get 'about' => 'authors#about', as: :about

   get 'authors' => 'authors#index', as: :authors

   get ':last_name' => 'posts#by_author', as: :author_posts

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><%= @title || "Dead Writer's Delorean" %></title>
  <!-- Custom Fonts -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>

<body id="<%= params[:controller] %>" class="<%= params[:action] %>">
    <!-- Navigation -->
  <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%= link_to "A Dead Poets Society Blog", root_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li>
                  <%= link_to "Home", root_path %>
              </li>
              <li>
                  <%= link_to "About", about_path %>
              </li>
              <li>
                  <%= link_to "Sample Post", post_path(:id => (1..5).to_a.sample.to_i) %>
              </li>
          </ul>
      </div>
        <!-- /.navbar-collapse -->
    </div>
      <!-- /.container -->
  </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
  <header class="intro-header">
    <div class="container">
        <div class="row">
          <div class="col-xs-12" style="height:300px;"></div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1><%= @title || "Dead Writer's Delorean" %></h1>
                    <hr class="small">
                    <h4 class="subheading"><%= @subheading || "An IronYard Academy Project Est. Summer 2015" %></h4>
                </div>
            </div>
        </div>
    </div>
  </header>

    <!-- Main Content -->
  <div class="container">
    <div class="row">
        <div class="main-content col-md-12">
            <%= yield %>
        </div>
    </div>
  </div>
  <hr>

    <!-- Footer -->
  <footer>
      <div class="container">
          <div class="row">
            <div id="footer_title" class="col-md-12">
              <h2>MOST POPULAR TIME TRAVELERS</h2>
            </div>
          </div>
          <div id="time_travelers" class="row">
            <div class="col-xs-12">
              <%= link_to author_posts_path(:last_name => "burgess") do %>
                <div id="burgess" class="col-xs-3 traveler"><h2>BURGESS</h2></div>
              <% end %>

              <%= link_to author_posts_path(:last_name => "kesey") do %>
                <div id="kesey" class="col-xs-3 col-xs-offset-3 traveler"><h2>KESEY</h2></div>
              <% end %>

              <%= link_to author_posts_path(:last_name => "vonnegut") do %>
                <div id="vonnegut" class="col-xs-3 col-xs-offset-6 traveler"><h2>VONNEGUT</h2></div>
              <% end %>

              <%= link_to author_posts_path(:last_name => "bradbury") do %>
                <div id="bradbury" class="col-xs-3 col-xs-offset-9 traveler"><h2>BRADBURY</h2></div>
              <% end %>
            </div>
          </div>
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <ul class="list-inline text-center">
                      <li>
                          <a href="#">
                              <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                              </span>
                          </a>
                      </li>
                  </ul>
                  <div class="col-lg-8 col-lg-pull-7">
                    <p class="copyright text-muted">Copyright &copy; DEAD POETS SOCIETY 2015. All Rights Reserved.</p>
                  </div>
              </div>
          </div>
      </div>
  </footer>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


</body>

</html>